app = "backend-zbwu9q"
primary_region = "cdg"

[build]
  image = "registry.fly.io/backend-zbwu9q:deployment-f2d6d705aad95d93bebe98bdb4151a4a"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

   [http_service.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 400

  [http_service.http_options]
    max_request_body_size = 10737418240 # 10GB in bytes

[[vm]]
  memory = '3gb'
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 1024

[mounts]
  source = "uploads_data_500gb"
  destination = "/uploads"
